### ISSUE TITLE
Fix: Data is not getting stored in Firestore

### ISSUE THREAD

**Issue by Indrajeet-S** [Indrajeet-S/leetcode-board#1]
For example, after doing a refresh or while accessing that problem ID again the page doesn't have persistence and data is not getting stored in the Firestore database. Find what is the exact issue is. 
Before: 
![image](https://github.com/user-attachments/assets/85572d7a-85e7-47d6-bfa0-a23b6b9cdaed)
After: 
![image](https://github.com/user-attachments/assets/f4fb7571-da7f-4b41-90dc-84a225333183)

Definition of done: 
- Data should be persistent and it should be stored in the Firestore database (for reference: I made the commit regarding persistence to local storage you can see)

**Comment by Macvncpro** [comment]
Hi,
    
    Could I give this a go?

**Comment by Indrajeet-S** [comment]
> Hi,
> 
> ```
> Could I give this a go?
> ```

Sure!

**Comment by Macvncpro** [comment]
Sorry I won't be able to do this.

**Comment by kelanialiyu** [comment]
Hi I would love to work on this can it be assigned to me?

**Comment by Indrajeet-S** [comment]
> Hi I would love to work on this can it be assigned to me?

Okay

**Comment by kelanialiyu** [comment]
I have made a pr can you check it out.
Also, I have two recommendations
1. add debounce to reduce the frequent writes to firebase.
2. move all firebase config to the env file

can you create issues for this so I can apply those fix

**Comment by Indrajeet-S** [comment]
Yeah, good suggestion! Thanks for this.

**Comment by Indrajeet-S** [comment]
I have created two issues regarding this. You can check! 
https://github.com/Indrajeet-S/leetcode-board/issues/20
https://github.com/Indrajeet-S/leetcode-board/issues/21
