### ISSUE TITLE
Move Firebase Configuration to Environment Variables

### ISSUE THREAD

**Issue by Indrajeet-S** [Indrajeet-S/leetcode-board#21]
Move all Firebase configuration values to environment variables for better security and easier configuration management.

**Comment by kelanialiyu** [comment]
can you assign this to me.

**Comment by kelanialiyu** [comment]
Also, can you create the following environment variables with their corresponding firebase config values on the hosting environment
NEXTJS_APP_API_KEY= {The API key (created already)}
NEXTJS_APP_AUTH_DOMAIN= {The auth domain (created already)}
NEXTJS_APP_PROJECT_ID= {The project id e.g. "leetboard-###"}
NEXTJS_APP_STORAGE_BUCKET= {The storage bucket e.g. "leetboard-###.appspot.com"} 
NEXTJS_APP_MESSAGING_SENDER_ID= {The messaging sender id e.g. "00000000"} 
NEXTJS_APP_APP_ID= {The app id e.g. "##########"} 
NEXTJS_APP_MEASUREMENT_ID={The measurement id e.g. "G-##########"}
