### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Indrajeet-S** [Indrajeet-S/leetcode-board#5]
README.md should have clear instructions regarding project setup. 
Maybe make a different PR on how one should contribute to this project in that add CONTRIBUTE.md (optional).

**Comment by Snehshishdutta** [comment]
Hi @Indrajeet-S ,I believe I can solve this issue. Could you please assign it to me?

**Comment by Indrajeet-S** [comment]
Sure, @Snehshishdutta go ahead!!

**Comment by RishiAnand108** [comment]
may i help update the readme so that it can provide a better idea and what stuff we are doing in the project.
